# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Network hypervisor
  hosts: hypervisors
  vars_files:
    - vars/network_common_hypervisor_vars.yaml
  roles:
    - systemd_networkd

- name: Configure Network observer
  hosts: observer
  vars_files:
    - vars/network_observer_vars.yml
  roles:
    - systemd_networkd

- name: Configure hosts and hostname
  hosts: all
  tasks:
      - name: Set hostname
        hostname:
            name: "{{ inventory_hostname }}"
            use: systemd
      - name: Build hosts file
        lineinfile:
            dest: /etc/hosts
            regexp: '.*{{ item }}$'
            line: "{{ hostvars[item].ip_addr }} {{item}}"
            state: present
        when: hostvars[item].ip_addr is defined
        loop: "{{ groups['all'] }}"
      - name: Add rbd in hosts file
        replace:
            path: /etc/hosts
            regexp: '^{{ ip_addr }} {{ inventory_hostname }}$'
            replace: '{{ ip_addr }} rbd {{ inventory_hostname }}'
