# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Network hypervisor
  hosts: hypervisors
  vars_files:
    - vars/network_common_hypervisor_vars.yaml
    - "vars/network_{{ network_bridge_type }}_hypervisor_vars.yaml"
  roles:
    - systemd_networkd

- name: Configure Network observer
  hosts: observer
  vars_files:
    - vars/network_observer_vars.yml
  roles:
    - systemd_networkd

- name: Configure OVS
  hosts: hypervisors
  tasks:
      - name: Ensures /opt/setup dir exists
        file: path=/opt/setup state=directory
        when: hostvars[inventory_hostname].network_bridge_type == "ovs"
      - name: Install setup_ovs.sh
        template:
            src: templates/setup_ovs.sh
            dest: /opt/setup/setup_ovs.sh
            owner: root
            group: root
            mode: '0755'
        when: hostvars[inventory_hostname].network_bridge_type == "ovs"
      - name: Install setup_ovs.server
        template:
            src: templates/setup_ovs.service
            dest: /etc/systemd/system
            owner: root
            group: root
            mode: '0644'
        when: hostvars[inventory_hostname].network_bridge_type == "ovs"
        notify:
            - Restart setup_ovs
  handlers:
      - name: Restart setup_ovs
        ansible.builtin.systemd:
            name: setup_ovs
            daemon_reload: yes
            state: restarted
            enabled: yes



- name: Configure hosts and hostname
  hosts: all
  tasks:
      - name: Set hostname
        hostname:
            name: "{{ inventory_hostname }}"
            use: systemd
      - name: Build hosts file
        lineinfile:
            dest: /etc/hosts
            regexp: '.*{{ item }}$'
            line: "{{ hostvars[item].ip_addr }} {{item}}"
            state: present
        when: hostvars[item].ip_addr is defined
        loop: "{{ groups['all'] }}"
      - name: Add rbd in hosts file
        replace:
            path: /etc/hosts
            regexp: '^{{ ip_addr }} {{ inventory_hostname }}$'
            replace: '{{ ip_addr }} rbd {{ inventory_hostname }}'

- name: Configure NTP
  hosts: all
  tasks:
      - name: Set NTP configuration in /etc/systemd/timesyncd.conf
        lineinfile:
            dest: /etc/systemd/timesyncd.conf
            regexp: '{{ item.regexp }}'
            line: '{{ item.line   }}'
            insertafter: '\[Time\]'
            backrefs: true
            create: true
            state: present
        with_items:
            - regexp: '^\s*#?\s*(NTP=).*$'
              line: 'NTP={{ ntp_servers }}'

            - regexp: '^\s*#?\s*(FallbackNTP=).*$'
              line: 'FallbackNTP={{ fallback_ntp_servers | default("") }}'
        notify:
            - Restart systemd timesyncd

  handlers:
      - name: Restart systemd timesyncd
        ansible.builtin.service:
            name: systemd-timesyncd
            state: restarted
