# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook includes the other playbooks that configure the cluster and
# allows you to configure the cluster from a single playbook. It is the first
# playbook to call.

---
- import_playbook: kernel_params_playbook.yaml
- import_playbook: network_playbook.yaml
- name: Restart all hosts
  hosts: all
  tasks:
      - block:
          - name: Restart
            reboot:
          - name: Wait for host to be online
            wait_for_connection:
        when: not apply_network_config
- import_playbook: cluster_playbook.yaml
- import_playbook: ceph_playbook.yaml
- import_playbook: libvirt_setup_playbook.yaml


