# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
---
- hosts: hypervisors
  vars:
     - disk_path: images/disk.qcow2
     - force: true
     - disk_name: disk
  roles:
     - seapath_import_vm_disk
