- import_playbook: cluster_setup_prerequisdebian.yaml
- import_playbook: cluster_setup_network.yaml
- import_playbook: cluster_setup_ceph.yaml
- import_playbook: cluster_setup_libvirt.yaml
- import_playbook: cluster_setup_ha.yaml
- import_playbook: cluster_setup_keys.yaml
- name: config elastic metricbeat
  hosts: cluster_machines
  tasks:
    - name: lineinfile in hosts file for logstash_seapath
      lineinfile:
        dest: /etc/hosts
        line: "{{ logstash_server_ip }} logstash_seapath"
        state: present
- name: Restart all hosts
  hosts: cluster_machines
  tasks:
    - name: Restart
      reboot:
    - name: Wait for host to be online
      wait_for_connection:

