# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook includes the other playbooks that configure the cluster and
# allows you to configure it from a single playbook. It is the first playbook to
# call.

---

- name: Check if we are using a correct seapath flavor
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  tasks:
    - name: Retrieve Seapath system version
      command: "uname -a"
      register: "uname_output"

    - name: Check if current Ansible branch is compatible
      fail:
        msg: "The current branch (main) is incompatible with the Debian version of SEAPATH. Please use the debian-main branch to configure this machine"
      failed_when:
        - uname_output.stdout | regex_search("Debian")

- import_playbook: cluster_setup_configure_hosts.yaml
- import_playbook: cluster_setup_ceph.yaml
- import_playbook: cluster_setup_libvirt.yaml
- import_playbook: cluster_setup_add_livemigration_user.yaml
- import_playbook: cluster_setup_ha.yaml
